# Generated by Django 4.2.5 on 2023-10-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple_images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimage',
            name='images',
            field=models.CharField(max_length=512),
        ),
    ]
